[build]
target = "web/index.html"
dist = "dist"

[watch]
watch = ["web", "lib"]
ignore = ["web/css"]

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", "if [[ ! $CF_PAGES ]]; then cd web; tailwindcss -i css/tailwind.css -o css/tailwind_compiled.css; fi"]
