[build]
target = "web/index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", "if [[ ! $CF_PAGES ]]; then tailwindcss -i web/css/tailwind.css -o web/css/tailwind_compiled.css; fi"]
