name = "chat"
type = "javascript"
workers_dev = true
compatibility_date = "2022-04-30"

kv_namespaces = [ 
  { binding = "chat", id = "386ff10a2c3c4380a767ec6b12a7fdc3", preview_id = "89fb8c2319fd46428559177c1a4eb259" }
]

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
