name = "chat"
workers_dev = true
compatibility_date = "2022-05-15"
compatibility_flags = [ "durable_object_fetch_allows_relative_url" ]
main = "worker/build/worker/shim.mjs"

[durable_objects]
bindings = [
  { name = "INBOX", class_name = "Inbox" }
]

[[migrations]]
tag = "v1"
new_classes = ["Inbox"]

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
cwd = "worker"
command = "cargo install -q worker-build && worker-build --release" # required

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
