[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
der = { version = "0.5.0", features = ["pem"] }
dioxus = { version = "0.2.3", features = ["fermi", "web"] }
dioxus-router = "0.2.2"
futures-util = "0.3.21"
getrandom = { version = "0.2.6", features = ["js"] }
pem-rfc7468 = "0.3.1"
pkcs8 = "0.8.0"
rand = "0.8.5"
rsa = { version = "0.6.1", features = ["pem"] }
web-sys = { version = "0.3.57", features = ["console", "Storage", "Window"] }

# For faster RSA key generation and manipulation
[profile.dev.package.num-bigint-dig]
opt-level = 3
