[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
der = { version = "0.5.0", features = ["pem"] }
dioxus = { version = "0.2.3", features = ["fermi", "web"] }
dioxus-router = "0.2.2"
futures-util = "0.3.21"
getrandom = { version = "0.2.6", features = ["js"] }
hex = "0.4.3"
pem-rfc7468 = "0.3.1"
pkcs8 = "0.8.0"
rand = "0.8.5"
rsa = { version = "0.6.1", features = ["pem", "serde"] }
serde = { version= "1.0", features = ["derive"] }
serde_json = { version= "1.0" }
sha2 = "0.10.2"
web-sys = { version = "0.3.57", features = ["Clipboard", "console", "Navigator", "Storage", "Window"] }

# For faster RSA key generation and manipulation
[profile.dev.package.num-bigint-dig]
opt-level = 3
